name: Build GifToSyphon with Custom API Key

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install --formula cmake
          brew install sdl2  # if SDL2 is a dependency for GifToSyphon

      - name: Inject API Key
        run: |
          sed -i '' "s/YOUR_API_KEY_PLACEHOLDER/${{ secrets.API_KEY }}/g" GifToSyphon/AppDelegate.m

      - name: Build GifToSyphon
        run: |
          xcodebuild -project GifToSyphon.xcodeproj -scheme GifToSyphon -configuration Release -derivedDataPath build

      - name: Zip the Application
        run: |
          cd build/Build/Products/Release
          zip -r GifToSyphon_Build.zip GifToSyphon.app

      - name: Upload GifToSyphon Build
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: GifToSyphon_Build
          path: build/Build/Products/Release/GifToSyphon_Build.zip
